name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Print .NET info
        run: |
          dotnet --info
          dotnet workload --info

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile
        run: dotnet publish -c Release -o ./publish

      - name: Upload compiled files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: publish/**
          retention-days: 5
          if-no-files-found: error

  build-pre-1:
    runs-on: ubuntu-latest

    steps:
      - name: Create generic txt
        run: |
          echo "--version ${{ github.sha }}" >> build-pre-1.txt
          mkdir app-data
          mv build-pre-1.txt app-data/build-pre-1.txt

      - name: Upload compiled files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-data
          path: app-data/**
          retention-days: 5
          if-no-files-found: error

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build-pre-1
      - build-dotnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download compiled files
        uses: actions/download-artifact@v2
        with:
          name: app
          path: publish

      - name: Extra files
        uses: actions/download-artifact@v2
        with:
          name: app-data
          path: publish

      - name: list all files
        run: ls -ltR

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: brmassa/dotnet7-docker-test:latest
