name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-pre-1:
    runs-on: ubuntu-latest

    steps:
    - name: Print .NET info
      run: dotnet --version >> app-1/build-pre-1.txt

    - name: Upload compiled files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-1
        path: app-1


  build:
    runs-on: ubuntu-latest
    needs: build-pre-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download compiled files
      uses: actions/download-artifact@v2
      with:
        name: app-1
        path: publish

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: brmassa/dotnet7-docker-test:${{ github.sha }}
